import { Check, GraduationCap, MessageCircle, Sparkles, UserRound } from 'lucide-react';
import { FORMAT_PREFERENCES, LEARNING_CHALLENGES, PREVIOUS_TUTORING_ISSUES, TUTOR_PREFERENCES } from '../config.ts';
import { MultiChoice, TextArea } from '../fields.tsx';
import { getInterviewLabel, getInterviewLabels } from '../labels.ts';
import { setTutoringHistory, toggleArrayValue, toggleExclusiveValue } from '../model.ts';
import { groupOptions, TUTOR_GROUPS } from '../presentation.ts';
import type { InterviewFormData, LearningFormat, Option } from '../types.ts';
import type { FormErrors } from '../validation.ts';
import './StepsConversation.css';

const FORMAT_COPY: Record<string, string> = { private: 'One-to-one support', 'small-group': 'More individual attention with peers', class: 'Structured group learning', advanced: 'Extension or targeted programs' };

function ChoiceGroups({ options, values, onToggle }: { options: readonly Option[]; values: readonly string[]; onToggle: (value: string) => void }) {
  return <div className="conversation-choice-groups">{groupOptions(options).map(group => <div key={group.heading}><h4>{group.heading}</h4><div>{group.options.map(option => { const selected = values.includes(option.value); return <button type="button" key={option.value} aria-pressed={selected} onClick={() => onToggle(option.value)}>{option.label}{selected ? <Check aria-hidden="true" /> : null}</button>; })}</div></div>)}</div>;
}

export function StepLearningPreferences({ data, onChange, studentName }: { data: InterviewFormData; errors: FormErrors; onChange: (next: InterviewFormData) => void; studentName: string }) {
  const tutorCore = TUTOR_PREFERENCES.filter(option => option.value !== 'no-preference');
  const challengeToggle = (value: string) => {
    const learningChallenges = toggleExclusiveValue(data.learningChallenges, value, ['nothing-specific', 'not-sure']);
    onChange({ ...data, learningChallenges, learningChallengesOther: learningChallenges.includes('other') ? data.learningChallengesOther : undefined });
  };
  const profileChallenges = getInterviewLabels(data.learningChallenges.filter(value => !['nothing-specific', 'not-sure', 'other'].includes(value))).slice(0, 4);
  const profileTutors = getInterviewLabels(data.tutorPreferences).slice(0, 4);
  const profileFormat = data.preferredFormats.map(value => value === 'not-sure' ? 'Let DA recommend' : getInterviewLabel(value));
  return <div className="conversation-step conversation-step--learning">
    <p className="conversation-pressure-note">We’re not looking for a perfect description — just anything you’ve noticed.</p>
    <section className="conversation-section"><header><span>01</span><div><h3>What can make learning harder?</h3><p>Choose anything that sounds familiar.</p></div></header><ChoiceGroups options={LEARNING_CHALLENGES} values={data.learningChallenges} onToggle={challengeToggle} />{data.learningChallenges.includes('other') ? <div className="conversation-conditional"><TextArea id="learning-challenges-other" label="What else should we know?" value={data.learningChallengesOther ?? ''} onChange={value => onChange({ ...data, learningChallengesOther: value })} /></div> : null}</section>
    <section className="conversation-section conversation-compact-section"><header><div><h3>Has {studentName} had tutoring before?</h3></div></header><div className="conversation-binary" role="group" aria-label="Previous tutoring"><button type="button" aria-pressed={data.hasHadTutoringBefore === true} onClick={() => onChange(setTutoringHistory(data, true))}>Yes{data.hasHadTutoringBefore === true ? <Check aria-hidden="true" /> : null}</button><button type="button" aria-pressed={data.hasHadTutoringBefore === false} onClick={() => onChange(setTutoringHistory(data, false))}>No{data.hasHadTutoringBefore === false ? <Check aria-hidden="true" /> : null}</button></div>{data.hasHadTutoringBefore ? <div className="conversation-conditional conversation-tutoring-followup"><TextArea id="previous-tutoring-worked" label="What worked well?" value={data.previousTutoringWorked ?? ''} onChange={value => onChange({ ...data, previousTutoringWorked: value })} /><MultiChoice id="previous-tutoring-issues" label="What didn’t work for them?" options={PREVIOUS_TUTORING_ISSUES} values={data.previousTutoringIssues} onToggle={value => onChange({ ...data, previousTutoringIssues: toggleArrayValue(data.previousTutoringIssues, value) })} /></div> : null}</section>
    <section className="conversation-section"><header><div><h3>Do you already have a learning format in mind?</h3><p>You don’t need to know — this is one of the things we can recommend during the consultation.</p></div></header><div className="conversation-format-grid">{FORMAT_PREFERENCES.filter(option => option.value !== 'not-sure').map(option => { const selected = data.preferredFormats.includes(option.value as LearningFormat); return <button type="button" key={option.value} aria-pressed={selected} onClick={() => onChange({ ...data, preferredFormats: toggleExclusiveValue(data.preferredFormats, option.value, ['not-sure']) as LearningFormat[] })}><GraduationCap aria-hidden="true" /><strong>{option.label}</strong><span>{FORMAT_COPY[option.value]}</span>{selected ? <Check className="format-check" aria-hidden="true" /> : null}</button>; })}</div><button type="button" className="conversation-full-soft-choice" aria-pressed={data.preferredFormats.includes('not-sure')} onClick={() => onChange({ ...data, preferredFormats: toggleExclusiveValue(data.preferredFormats, 'not-sure', ['not-sure']) as LearningFormat[] })}>I’m not sure — please recommend what suits {studentName}.{data.preferredFormats.includes('not-sure') ? <Check aria-hidden="true" /> : null}</button></section>
    <section className="conversation-section"><header><span>02</span><div><p className="conversation-section-kicker">WHO MIGHT {studentName.toUpperCase()} LEARN BEST WITH?</p><h3>What kind of tutor tends to bring out the best in {studentName}?</h3></div></header><div className="conversation-choice-groups">{groupOptions(tutorCore, TUTOR_GROUPS).map(group => <div key={group.heading}><h4>{group.heading}</h4><div>{group.options.map(option => { const selected = data.tutorPreferences.includes(option.value); return <button type="button" key={option.value} aria-pressed={selected} onClick={() => onChange({ ...data, tutorPreferences: toggleExclusiveValue(data.tutorPreferences, option.value, ['no-preference']) })}>{option.label}{selected ? <Check aria-hidden="true" /> : null}</button>; })}</div></div>)}</div><button type="button" className="conversation-full-soft-choice" aria-pressed={data.tutorPreferences.includes('no-preference')} onClick={() => onChange({ ...data, tutorPreferences: toggleExclusiveValue(data.tutorPreferences, 'no-preference', ['no-preference']) })}>No preference — please recommend who suits {studentName}.{data.tutorPreferences.includes('no-preference') ? <Check aria-hidden="true" /> : null}</button><p className="conversation-matching-note"><UserRound aria-hidden="true" />We consider teaching style, subject expertise and personality when matching students.</p></section>
    <section className="conversation-notes-pair"><div><MessageCircle aria-hidden="true" /><TextArea id="tutor-preference-notes" label={`Anything we should consider when matching ${studentName}?`} hint="Personality, previous experiences, school circumstances, scheduling considerations or anything else that may help." value={data.tutorPreferenceNotes ?? ''} onChange={value => onChange({ ...data, tutorPreferenceNotes: value })} /></div><div><Sparkles aria-hidden="true" /><TextArea id="anything-else" label="Anything else you’d like us to know before we speak?" hint="Optional" value={data.anythingElse ?? ''} onChange={value => onChange({ ...data, anythingElse: value })} /></div></section>
    {(profileChallenges.length || profileTutors.length || profileFormat.length) ? <aside className="conversation-profile-preview"><div><span>BASED ON WHAT YOU’VE TOLD US SO FAR</span><h3>{studentName}’s learning profile</h3></div><div className="profile-columns"><section><h4>Likely to benefit from</h4>{profileChallenges.length ? <ul>{profileChallenges.map(label => <li key={label}>{label}</li>)}</ul> : <p>We’ll explore this together.</p>}</section><section><h4>Tutor match</h4>{profileTutors.length ? <ul>{profileTutors.map(label => <li key={label}>{label}</li>)}</ul> : <p>Let DA recommend.</p>}</section><section><h4>Format</h4>{profileFormat.length ? <ul>{profileFormat.map(label => <li key={label}>{label}</li>)}</ul> : <p>We’ll discuss the options.</p>}</section></div><p>We’ll discuss this with you before recommending a starting point.</p></aside> : null}
  </div>;
}
