export const mathsClassOptions = [
  {
    title: 'Private Maths Tuition',
    short: 'Personalised support at your pace.',
    description: 'One-to-one lessons for students who need targeted explanations, tailored practice and a pace built around their own goals. Tutors can slow down, extend a concept or rehearse an assessment skill exactly when it is needed, so students understand the method rather than simply copying a solution.',
    image: '/english-page/images/subjects/english/class-private.png',
    alt: 'A tutor working one-to-one with a student',
    tone: '#A98BEC',
    softTone: '#EEE8FF',
    icon: 'private',
    stats: [['Best for', 'Targeted explanation and confidence'], ['Class size', 'One-to-one support'], ['Pace', 'Adapted to the student'], ['Style', 'Personalised and assessment-focused']],
  },
  {
    title: 'Small-Group Maths Classes',
    short: 'Weekly momentum with expert support.',
    description: 'A consistent weekly class that builds strong foundations, gives students room to ask questions and keeps them moving forward. Students learn alongside motivated peers while still receiving clear feedback, carefully sequenced practice and the chance to explain the reasoning behind each step.',
    image: '/english-page/images/subjects/english/class-gat.png',
    alt: 'Students working together in a DA Tuition class',
    tone: '#7ECDA7',
    softTone: '#E8F7EF',
    icon: 'group',
    stats: [['Best for', 'Students who value routine and discussion'], ['Class size', 'Small-group learning'], ['Pace', 'Clear weekly progression'], ['Style', 'Collaborative and structured']],
  },
  {
    title: 'School Focus Classes',
    short: 'Support matched to their school program.',
    description: 'Students from the same school learn in step with their classroom program, reinforcing the exact concepts, assessments and expectations they are facing. This makes every session immediately relevant while giving students more time to practise, ask questions and prepare with peers in the same cohort.',
    image: '/english-page/images/subjects/english/class-focus.png',
    alt: 'A small group of students learning with a tutor',
    tone: '#E99BC3',
    softTone: '#FCEAF3',
    icon: 'focus',
    stats: [['Best for', 'Students needing school-aligned support'], ['Class size', 'Same-school cohort'], ['Pace', 'Aligned to school assessments'], ['Style', 'Relevant and collaborative']],
  },
  {
    title: 'Selective & Trial Preparation',
    short: 'Fast, focused preparation for top performance.',
    description: 'Purpose-built preparation for selective-school and school trial exams, with timed practice, challenging questions and clear feedback. Students develop efficient problem-solving habits, learn to recognise question types and build the composure to show their strongest work under pressure.',
    image: '/english-page/images/subjects/english/class-bullet.png',
    alt: 'Students completing focused classroom work',
    tone: '#F2A764',
    softTone: '#FFF0E2',
    icon: 'selective',
    stats: [['Best for', 'Driven students preparing for competitive exams'], ['Class size', 'Focused preparation group'], ['Pace', 'Purposeful and exam-led'], ['Style', 'Challenging and strategic']],
  },
] as const;
