import { useMemo, useRef } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import { Navigation, ArrowRight, BusFront, CarFront, ChevronDown, MapPin, TrainFront } from 'lucide-react';
import { PHYSICAL_CENTRES, resolveCentre, shouldShowCentreSwitcher } from '@/data/physical-centres';
import { WayfinderMap } from './WayfinderMap';
import { getCentreStatus } from './centre-status';
import './wayfinder.css';

export default function WayfinderLocationsPage() {
 const [params,setParams]=useSearchParams(); const resolved=useMemo(()=>resolveCentre(params.get('centre')),[params]); const { centre, group, effective }=resolved; const reduced=useReducedMotion(); const status=getCentreStatus(effective.hours!, effective.timezone);
 const communityRef = useRef<HTMLElement>(null);
 const { scrollYProgress: communityProgress } = useScroll({ target: communityRef, offset: ['start start', 'end end'] });
 const localCopyOpacity = useTransform(communityProgress, [0, .42, .55], [1, 1, 0], { clamp: true });
 const regionalCopyOpacity = useTransform(communityProgress, [.57, .75], [0, 1], { clamp: true });
 const select=(id:string)=>{ const next=new URLSearchParams(params); next.set('centre',id); setParams(next); };
 return <main className="wayfinder" style={{'--gold':'#d6a921'} as React.CSSProperties}>
  <section className="wayfinder-hero" aria-labelledby="wayfinder-title"><WayfinderMap selectedCentre={centre} variant="hero"/><div className="wayfinder-route-exit" aria-hidden="true"><i /></div><div className="wayfinder-navline">DA <span>WAYFINDER</span><b>01 / EXPLORE</b></div><div className="wayfinder-hero-copy"><p>DA TUITION LOCATIONS</p><h1 id="wayfinder-title">Find your way to DA.</h1><div className="wayfinder-route-copy">Choose a centre, plan your visit, and find everything you need before you arrive.</div></div>
   <motion.div className="wayfinder-destination" key={centre.id} initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}}><p>CURRENT DESTINATION</p><span>{status.heading.toUpperCase()}</span><strong>{status.detail}</strong><h2>{group.displayName}<em>{centre.buildingLabel}</em></h2><address>{centre.addressLines[0]}<br/>{centre.addressLines[1]}</address><a href={centre.directionsUrl} target="_blank" rel="noreferrer">GET DIRECTIONS <Navigation size={15}/></a></motion.div>
   {shouldShowCentreSwitcher(PHYSICAL_CENTRES)&&<label className="wayfinder-selector"><span>CHANGE CENTRE</span><select aria-label="Change centre" value={centre.id} onChange={e=>select(e.target.value)}>{PHYSICAL_CENTRES.map(item=><option key={item.id} value={item.id}>{group.displayName} — {item.buildingLabel}</option>)}</select><ChevronDown size={15}/></label>}
  </section>
  <section className="wayfinder-arrive" aria-labelledby="arrive-title"><div className="wayfinder-spine" aria-hidden="true"/><div className="wayfinder-arrive-intro"><p className="wayfinder-step">02 / ARRIVE</p><h2 id="arrive-title">The route to your<br/>next session.</h2><p className="wayfinder-editorial">Plan your trip before you leave, with transport and parking information for your selected centre.</p></div><div className="wayfinder-diagram"><div className="wayfinder-route-node"><span><TrainFront size={19}/></span><div><small>ARRIVE BY TRAIN</small><b>{effective.arrival?.stationLabel}</b></div></div><div className="wayfinder-route-node"><span><BusFront size={19}/></span><div><small>CONTINUE BY</small><b>{effective.arrival?.routeLabel}</b></div></div><div className="wayfinder-route-node is-destination"><span><MapPin size={19}/></span><div><small>DA TUITION</small><b>{centre.buildingLabel}</b><p>{centre.addressLines[0]}<br/>{centre.addressLines[1]}</p></div></div></div><dl className="wayfinder-arrive-details">{effective.arrival?.notes?.map(note=>{const Icon=note.label==='Train'?TrainFront:note.label==='Bus'?BusFront:CarFront; const detail=note.label==='Train'?'Nearest-station access is via Canley Vale Station.':note.detail; return <div key={note.label}><Icon size={20}/><div><dt>{note.label}</dt><dd>{detail}</dd></div></div>})}</dl></section>
  <section className="wayfinder-when" aria-labelledby="when-title"><div className="wayfinder-when-status"><div className="wayfinder-today"><p>TODAY / {new Intl.DateTimeFormat('en-AU',{timeZone:effective.timezone,weekday:'long'}).format(new Date())}</p><strong>{status.heading}</strong><span>{status.detail}</span><div className="wayfinder-timebar" aria-hidden="true"><i style={{left:`${Math.max(3,Math.min(97,(status.currentMinutes-540)/750*100))}%`}}/></div></div><dl className="wayfinder-week">{effective.hours?.map(item=><div key={item.day} className={item.day===new Intl.DateTimeFormat('en-AU',{timeZone:effective.timezone,weekday:'long'}).format(new Date())?'is-today':''}><dt>{item.day}</dt><dd>{item.label}</dd></div>)}</dl></div><div className="wayfinder-when-intro"><p>03 / WHEN</p><h2 id="when-title">Practical details,<br/><em>beautifully clear.</em></h2></div></section>
  <section className="wayfinder-community" ref={communityRef} aria-labelledby="community-title"><div className="wayfinder-community__sticky"><WayfinderMap selectedCentre={centre} variant="community" communityProgress={communityProgress}/><div className="wayfinder-community__copy"><p>04 / COMMUNITY</p><motion.div className="wayfinder-community__local-copy" style={{ opacity: localCopyOpacity }}><h2 id="community-title">Local community.</h2><span>Students join DA from schools across the surrounding Fairfield area.</span></motion.div><motion.div className="wayfinder-community__regional-copy" aria-hidden="true" style={{ opacity: regionalCopyOpacity }}><h2>From here,<br/>the community reaches<br/>across Sydney.</h2><span>DA’s community extends well beyond the immediate neighbourhood.</span></motion.div></div><div className="wayfinder-community__caption" aria-hidden="true"><span>CANLEY HEIGHTS</span><i/><span>WIDER COMMUNITY</span></div></div></section>
  <section className="wayfinder-ready"><WayfinderMap selectedCentre={centre} variant="ready"/><div><p>05 / READY</p><span>YOU’VE FOUND US</span><h2>Your next step starts here.</h2><div className="ready-actions"><Link to={effective.bookingPath ?? '/book-interview'}>BOOK AN INTERVIEW <ArrowRight size={16}/></Link><a href={centre.directionsUrl} target="_blank" rel="noreferrer">GET DIRECTIONS</a></div><address>{centre.addressLines[0]}<br/>{centre.addressLines[1]}</address></div></section>
 </main>;
}
