import { FormEvent, useDeferredValue, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ArrowRight, BarChart3, BookOpen, Check, CheckCircle2, Menu, Search, Sparkles, UserRound, Users, X } from 'lucide-react';
import { allFaqQuestions, FaqQuestion, journeyQuestions, rankJourneyQuestions } from './faqData';
import './faq-answer-desk.css';

gsap.registerPlugin(ScrollTrigger);
const nodePositions: Record<string, { x: number; y: number; align?: 'right' }> = { cost:{x:17,y:20,align:'right'}, attention:{x:76,y:22}, behind:{x:10,y:49,align:'right'}, progress:{x:78,y:50}, 'tutor-match':{x:18,y:77,align:'right'}, 'class-size':{x:48,y:84}, ahead:{x:78,y:76} };
const categoryLabels: Record<string,string> = { all:'All', start:'Getting started', programs:'Programs', fees:'Fees', classes:'Classes', teachers:'Teachers', results:'Progress', safety:'Safety' };
function iconFor(q:FaqQuestion){if(q.id==='cost')return <span className="faq-currency">$</span>;if(q.id==='attention'||q.id==='class-size')return <Users/>;if(q.id==='progress'||q.id==='ahead')return <BarChart3/>;if(q.id==='tutor-match'||q.id==='behind')return <UserRound/>;return <BookOpen/>}

function QuestionConstellation({selectedId,completed,matches,onSelect}:{selectedId:string;completed:Set<string>;matches:Set<string>;onSelect:(q:FaqQuestion)=>void}){
 const rootRef=useRef<HTMLElement>(null); const hasSearch=matches.size>0;
 useLayoutEffect(()=>{const root=rootRef.current;if(!root||innerWidth<768||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=gsap.context(()=>{gsap.timeline({scrollTrigger:{trigger:root,start:'top 72%',once:true}}).from('.faq-constellation-heading',{opacity:0,y:18,duration:.55,ease:'power2.out'}).from('.faq-orbit-centre',{opacity:0,scale:.94,duration:.45},'-=.25').from('.faq-orbit-loop',{strokeDashoffset:760,duration:.8},'-=.2').from('.faq-question-node',{opacity:0,y:12,stagger:.07,duration:.42},'-=.55').from('.faq-connector',{strokeDashoffset:330,stagger:.05,duration:.65},'-=.55')},root);return()=>ctx.revert()},[]);
 useEffect(()=>{const root=rootRef.current;if(!root||matchMedia('(pointer: coarse)').matches||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const move=(e:PointerEvent)=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const b=root.getBoundingClientRect();const dx=(e.clientX-b.left)/b.width-.5,dy=(e.clientY-b.top)/b.height-.5;root.querySelectorAll<HTMLElement>('.faq-question-node').forEach((n,i)=>{const a=3+i%3;n.style.setProperty('--pointer-x',`${dx*a}px`);n.style.setProperty('--pointer-y',`${dy*a}px`)})})};root.addEventListener('pointermove',move,{passive:true});return()=>{cancelAnimationFrame(frame);root.removeEventListener('pointermove',move)}},[]);
 return <section ref={rootRef} id="question-constellation" className="faq-constellation" aria-labelledby="constellation-title"><div className="faq-constellation-heading"><h2 id="constellation-title">What are you wondering about?</h2><span/></div><div className="faq-orbit" onMouseLeave={e=>e.currentTarget.removeAttribute('data-hovering')}><svg className="faq-connectors" viewBox="0 0 1000 650" preserveAspectRatio="none" aria-hidden="true">{journeyQuestions.slice(0,7).map(q=>{const p=nodePositions[q.id];return <path key={q.id} className="faq-connector" d={`M 500 325 Q ${(p.x*10+500)/2} ${(p.y*6.5+325)/2-20} ${p.x*10} ${p.y*6.5}`}/>} )}</svg><div className="faq-orbit-centre" aria-hidden="true"><svg viewBox="0 0 260 150"><path className="faq-orbit-loop" d="M14 79C18 29 66 5 137 10c71 5 111 34 109 70-2 39-45 64-117 62C55 140 10 119 14 79Z"/></svg><span>What’s on<br/>your mind?</span></div><div className="faq-thought-stream">{journeyQuestions.slice(0,7).map(q=>{const p=nodePositions[q.id],match=matches.has(q.id);return <button key={q.id} type="button" style={{'--node-x':`${p.x}%`,'--node-y':`${p.y}%`} as React.CSSProperties} className={`faq-question-node ${p.align?'is-right-aligned':''} ${selectedId===q.id?'is-selected':''} ${completed.has(q.id)?'is-complete':''} ${match?'is-match':''} ${hasSearch&&!match?'is-dimmed':''}`} onClick={()=>onSelect(q)} onMouseEnter={e=>e.currentTarget.closest('.faq-orbit')?.setAttribute('data-hovering',q.id)} aria-pressed={selectedId===q.id}><span className="faq-node-icon">{completed.has(q.id)?<Check/>:iconFor(q)}</span><span className="faq-node-copy">{q.question}</span><span className="faq-node-cue">Let’s find out <ArrowRight/></span></button>})}</div></div></section>
}
function ProgressReport(){return <div className="faq-report"><strong>Weekly Progress Report</strong>{['Understanding','Accuracy','Practice','Confidence'].map((l,r)=><div key={l}><span>{l}</span><span aria-label={`${4-r%2} out of 5`}>{Array.from({length:5},(_,i)=><i key={i} className={i<4-r%2?'filled':''}>★</i>)}</span></div>)}<svg viewBox="0 0 180 32" aria-hidden="true"><path d="M2 27 L30 20 L58 23 L88 11 L118 15 L148 7 L178 3"/></svg></div>}
function AttentionJourney({onComplete}:{onComplete:()=>void}){const rootRef=useRef<HTMLDivElement>(null);useLayoutEffect(()=>{const root=rootRef.current;if(!root||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const ctx=gsap.context(()=>{gsap.fromTo('.faq-journey-line path',{strokeDashoffset:900},{strokeDashoffset:0,ease:'none',scrollTrigger:{trigger:'.faq-story',start:'top 76%',end:'bottom 66%',scrub:.6}});gsap.from('.faq-story-stage',{opacity:.45,y:20,stagger:.12,scrollTrigger:{trigger:'.faq-story',start:'top 72%'},duration:.65,ease:'power2.out'})},root);return()=>ctx.revert()},[]);return <div ref={rootRef} className="faq-attention-journey"><div className="faq-answer-intro"><strong>Yes. Because we intentionally keep our classes small and we know every student.</strong><p>It’s not just about numbers — it’s about knowing their strengths, understanding their gaps, and guiding them with the right support.</p></div><div className="faq-story"><svg className="faq-journey-line" viewBox="0 0 900 200" preserveAspectRatio="none" aria-hidden="true"><path d="M10 130 C150 128 170 45 310 95 S520 170 610 104 S770 35 890 85"/></svg><article className="faq-story-stage"><span>1 · Know them</span><img src="/images/faq/faq-human-answer-focus-with-tables.png" alt="A DA tutor listening closely while working with a student"/><p>We get to know every student — their learning style, confidence and goals.</p></article><article className="faq-story-stage"><span>2 · Teach them</span><img src="/images/faq/faq-hero-tutor-student-brow-touchup.png" alt="A tutor guiding a student through mathematics work"/><p>Lessons are tailored to their current level with clear explanations and practice that builds understanding.</p></article><article className="faq-story-stage"><span>3 · Track them</span><ProgressReport/><p>We monitor progress closely and parents receive feedback after every lesson.</p></article></div><div className="faq-completion"><CheckCircle2/><h3>That answered it!</h3><button type="button" onClick={onComplete}>I have another question <ArrowRight/></button></div></div>}
function QuestionJourney({question,onComplete}:{question:FaqQuestion;onComplete:()=>void}){return <section id="question-journey" className="faq-journey" aria-labelledby="journey-heading"><div className="faq-journey-steps" aria-label="Question journey progress">{['Question','Our Approach','See It in Action','Your Answer'].map((l,i)=><div key={l} className={i===0?'active':''}><span>{i+1}</span><b>{l}</b></div>)}</div><div className="faq-journey-heading"><p>Your question</p><h2 id="journey-heading">{question.question}</h2><i/></div>{question.journeyType==='attention'?<AttentionJourney onComplete={onComplete}/>:<div className="faq-default-answer"><Sparkles/><div><h3>{question.shortAnswer}</h3><p>{question.answer}</p>{question.links?.map(l=><Link key={l.href} to={l.href}>{l.label}<ArrowRight/></Link>)}</div><button type="button" onClick={onComplete}>That answered it <Check/></button></div>}</section>}
function AllQuestionsDrawer({open,onClose,onSelect}:{open:boolean;onClose:()=>void;onSelect:(q:FaqQuestion)=>void}){const[category,setCategory]=useState('all'),[openId,setOpenId]=useState<string|null>(null);const questions=category==='all'?allFaqQuestions:allFaqQuestions.filter(q=>q.category===category);useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();document.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=''}},[open,onClose]);return <div className={`faq-drawer-shell ${open?'is-open':''}`} aria-hidden={!open}><button className="faq-drawer-backdrop" type="button" onClick={onClose} tabIndex={open?0:-1} aria-label="Close all questions"/><aside className="faq-drawer" role="dialog" aria-modal="true" aria-labelledby="all-questions-title"><header><div><span>DA Answer Desk</span><h2 id="all-questions-title">All questions</h2></div><button type="button" onClick={onClose} aria-label="Close"><X/></button></header><nav aria-label="FAQ categories">{Object.entries(categoryLabels).map(([id,l])=><button type="button" key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{l}</button>)}</nav><div className="faq-drawer-list">{questions.map(q=><article key={q.id}><button type="button" aria-expanded={openId===q.id} onClick={()=>setOpenId(openId===q.id?null:q.id)}><span>{q.question}</span><span>{openId===q.id?'−':'+'}</span></button>{openId===q.id?<div><p>{q.answer}</p><button type="button" onClick={()=>{onSelect(q);onClose()}}>Follow this question <ArrowRight/></button></div>:null}</article>)}</div></aside></div>}
export default function FAQAnswerDesk(){const[query,setQuery]=useState(''),deferred=useDeferredValue(query),[selected,setSelected]=useState(()=>journeyQuestions.find(q=>q.id==='attention')!),[completed,setCompleted]=useState<Set<string>>(()=>new Set()),[drawerOpen,setDrawerOpen]=useState(false);const results=useMemo(()=>rankJourneyQuestions(deferred),[deferred]),matches=useMemo(()=>new Set(results.map(r=>r.question.id)),[results]);const select=(q:FaqQuestion)=>{setSelected(q);setTimeout(()=>document.getElementById('question-journey')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}),40)};const submit=(e:FormEvent)=>{e.preventDefault();if(results[0])select(results[0].question);else document.getElementById('question-constellation')?.scrollIntoView({behavior:'smooth'})};const complete=()=>{setCompleted(c=>new Set(c).add(selected.id));document.getElementById('question-constellation')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'})};return <main className="faq-answer-desk"><section className="faq-hero"><div className="faq-hero-copy"><p>DA Answer Desk</p><h1>Start with what’s<br/>on your mind.</h1><div>Clear answers before you commit, about classes, fees, teachers, progress and getting started.</div><em>We’re here to help.</em></div><div className="faq-hero-image"><img src="/images/faq/faq-hero-tutor-student-brow-touchup.png" alt="A DA Tuition tutor and student working through mathematics together"/></div><div className="faq-search-wrap"><form onSubmit={submit}><label htmlFor="faq-search">Search frequently asked questions</label><Search aria-hidden="true"/><input id="faq-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search in your own words. Try “class size”"/><span aria-live="polite">{query.trim()?`${results.length} related thought${results.length===1?'':'s'}`:''}</span></form><button type="button" onClick={()=>setDrawerOpen(true)}><Menu/> View all questions</button></div></section><QuestionConstellation selectedId={selected.id} completed={completed} matches={matches} onSelect={select}/><div className="faq-selection-thread" aria-hidden="true"><span/></div><QuestionJourney key={selected.id} question={selected} onComplete={complete}/><AllQuestionsDrawer open={drawerOpen} onClose={()=>setDrawerOpen(false)} onSelect={select}/></main>}
