import { useLayoutEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import gsap from "gsap";
import { Flip } from "gsap/Flip";
import { finaleConfig, type FinaleLayerRegistrar } from "./finaleConfig";
import { finaleInteractionTiming as timing, finaleYears, type FinaleYear } from "./finaleYears";
import "./FinaleScene.css";
gsap.registerPlugin(Flip);

const streaks=[18,29,43,58,74,84];
const fragments=[[42,21,10],[59,17,7],[47,35,6],[55,41,11],[39,54,8],[63,59,6],[45,72,12],[57,77,9],[36,83,6],[66,31,8]];

function YearContent({year,state}:{year:FinaleYear;state:"active"|"outgoing"}){
 return <article className={`hs-finale__year-content hs-finale__year-content--${state}`} data-year-content={state} style={{"--year-color":year.color} as React.CSSProperties}>
  <img className="hs-finale__content-wash" src={year.wash} alt=""/><span className="hs-finale__ghost-number" aria-hidden="true">{year.number}</span>
  <div className="hs-finale__content-piece hs-finale__content-intro"><p>YEAR {year.number}</p><h3>{year.title}</h3><strong>{year.supporting}</strong></div>
  <div className="hs-finale__content-columns"><section className="hs-finale__content-piece"><h4>WHAT THEY’RE LEARNING</h4><ul>{year.learning.map(item=><li key={item}>{item}</li>)}</ul></section><section className="hs-finale__content-piece"><h4>WHAT WE DO AT DA</h4><ul>{year.support.map(item=><li key={item}>{item}</li>)}</ul></section></div>
  <blockquote className="hs-finale__content-piece">“{year.closing}”</blockquote>
  {year.year===10&&<Link className="hs-finale__hsc-link hs-finale__content-piece" to="/hsc-excellence">Explore our HSC program <span aria-hidden="true">→</span></Link>}
 </article>;
}

export function FinaleScene({register}:{register:FinaleLayerRegistrar}){
 const rootRef=useRef<HTMLElement|null>(null),headingRef=useRef<HTMLElement|null>(null);
 const yearRefs=useRef<(HTMLButtonElement|null)[]>([]),arrowRefs=useRef<(HTMLImageElement|null)[]>([]);
 const transitionRef=useRef<gsap.core.Timeline|null>(null),flipStateRef=useRef<ReturnType<typeof Flip.getState>|null>(null),directionRef=useRef(1);
 const [activeYear,setActiveYear]=useState<number|null>(null),[outgoingYear,setOutgoingYear]=useState<number|null>(null),[hasSelectedYear,setHasSelectedYear]=useState(false);
 const registerScene=(node:HTMLElement|null)=>{rootRef.current=node;(register("scene") as (node:HTMLElement|null)=>void)(node)};
 const registerHeading=(node:HTMLElement|null)=>{headingRef.current=node;(register("final-heading") as (node:HTMLElement|null)=>void)(node)};

 useLayoutEffect(()=>{if(!hasSelectedYear||!flipStateRef.current)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;Flip.from(flipStateRef.current,{duration:reduced?0:timing.layout,ease:"power3.inOut",absolute:true,scale:true,nested:true});flipStateRef.current=null},[hasSelectedYear]);
 useLayoutEffect(()=>{if(activeYear===null||!rootRef.current)return;transitionRef.current?.kill();const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,direction=directionRef.current,root=rootRef.current,d=reduced?.01:1;const active=root.querySelector<HTMLElement>('[data-year-content="active"]'),outgoing=root.querySelector<HTMLElement>('[data-year-content="outgoing"]'),pieces=active?.querySelectorAll<HTMLElement>(".hs-finale__content-piece")??[],wash=active?.querySelector<HTMLElement>(".hs-finale__content-wash"),selected=yearRefs.current[activeYear],inactive=yearRefs.current.filter((_,i)=>i!==activeYear);const tl=gsap.timeline({defaults:{overwrite:"auto"},onComplete:()=>setOutgoingYear(null)});transitionRef.current=tl;if(outgoing)tl.to(outgoing,{xPercent:-direction*13,autoAlpha:0,duration:timing.contentExit*d,ease:"power3.in"},0);if(selected)tl.fromTo(selected,{scale:1},{scale:1.08,duration:timing.bubbleReact*d,ease:"power2.out",yoyo:true,repeat:1},0);tl.to(inactive,{opacity:.56,duration:.18*d},0).to(arrowRefs.current,{opacity:.92,scale:1.08,duration:.16*d,stagger:.045*d,filter:`drop-shadow(0 0 5px ${finaleYears[activeYear].color})`},.05*d);if(active)tl.fromTo(active,{xPercent:direction*13,autoAlpha:0},{xPercent:0,autoAlpha:1,duration:timing.contentEnter*d,ease:"power4.out"},outgoing?.14*d:.06*d);if(wash)tl.fromTo(wash,{opacity:0,scale:.88,clipPath:direction>0?"inset(0 100% 0 0)":"inset(0 0 0 100%)"},{opacity:.16,scale:1,clipPath:"inset(0 0% 0 0%)",duration:.48*d,ease:"power3.out"},.1*d);if(pieces.length)tl.fromTo(pieces,{y:14,opacity:0},{y:0,opacity:1,duration:.28*d,stagger:timing.contentStagger*d,ease:"power3.out"},.17*d);return()=>{tl.kill()}},[activeYear]);
 const selectYear=(index:number)=>{if(index===activeYear){gsap.fromTo(yearRefs.current[index],{scale:1},{scale:1.045,duration:.14,yoyo:true,repeat:1,ease:"power2.inOut"});return}directionRef.current=activeYear===null||index>activeYear?1:-1;if(!hasSelectedYear){flipStateRef.current=Flip.getState(yearRefs.current.filter(Boolean));const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;gsap.to(headingRef.current,{x:reduced?0:-70,autoAlpha:0,clipPath:"inset(0 100% 0 0)",duration:reduced?.01:timing.headlineExit,ease:"power3.in"});setHasSelectedYear(true)}setOutgoingYear(activeYear);setActiveYear(index)};
 const active=activeYear===null?null:finaleYears[activeYear],outgoing=outgoingYear===null?null:finaleYears[outgoingYear];
 return <section className={`hs-finale hs-finale--student-only${hasSelectedYear?" hs-finale--exploring":""}`} ref={registerScene} aria-label="The Years 7 to 10 journey" style={{"--active-color":active?.color??"#c99125"} as React.CSSProperties}>
  <div className="hs-finale__background"/><svg className="hs-finale__hero" viewBox="0 0 1200 1000" ref={register("hero") as React.Ref<SVGSVGElement>} role="img" aria-label="A DA Tuition student surrounded by a multicolour watercolour burst"><defs><clipPath id="hs-finale-reveal"><path ref={register("reveal-0") as React.Ref<SVGPathElement>} d="M600 370c102-83 265-53 329 63 69 124 9 281-107 350-139 83-343 43-410-99-62-131 55-246 188-314Z"/><path ref={register("reveal-1") as React.Ref<SVGPathElement>} d="M425 252c78-75 198-111 295-61 80 42 103 149 56 225-64 103-229 130-321 50-65-57-91-154-30-214Z"/><path ref={register("reveal-2") as React.Ref<SVGPathElement>} d="M352 603c104-66 264-38 326 73 57 101 18 245-86 297-122 61-301 8-344-115-36-102 17-200 104-255Z"/></clipPath></defs><g clipPath="url(#hs-finale-reveal)"><image className="hs-finale__composite" ref={register("burst") as React.Ref<SVGImageElement>} href={finaleConfig.compositeAsset} x="270" y="0" width="660" height="1000" preserveAspectRatio="xMidYMid meet"/></g></svg>
  <header className="hs-finale__final-heading" ref={registerHeading}><p>YEARS 7–10</p><h3>The Four Years<br/>That Change Everything.</h3><span>Choose a year to explore ↓</span></header>
  <div className="hs-finale__content-stage" aria-live="polite">{outgoing&&<YearContent year={outgoing} state="outgoing"/>}{active&&<YearContent year={active} state="active"/>}</div>
  <div className="hs-finale__years" aria-label="Choose a school year"><span className="hs-finale__navigator-line" aria-hidden="true"/>{[0,1,2].map(i=><img key={i} className={`hs-finale__year-arrow hs-finale__year-arrow--${i+1}`} ref={node=>{arrowRefs.current[i]=node;(register(`year-arrow-${i}`) as (node:HTMLImageElement|null)=>void)(node)}} src="/high-school-journey/finale/year-journey-arrow-ai.png" alt=""/>)}{finaleYears.map((year,i)=><button key={year.number} type="button" aria-label={`Explore Year ${year.year}`} aria-pressed={activeYear===i} className={`hs-finale__year hs-finale__year--${i+1} hs-finale__year--${year.tone}`} onClick={()=>selectYear(i)} ref={node=>{yearRefs.current[i]=node;(register(`year-${i}`) as (node:HTMLElement|null)=>void)(node)}}><img className="hs-finale__bubble-image" src={`/high-school-journey/finale/year-${year.number}-${year.tone}-bubble-ai.png`} alt=""/><span className="hs-finale__year-copy"><strong>{year.number}</strong><span>YEAR {year.year}</span><em>{year.title}</em></span><img className="hs-finale__year-icon" src={year.icon} alt=""/></button>)}</div>
  {(["left","right"] as const).map(side=><svg key={side} className={`hs-finale__curtain hs-finale__curtain--${side}`} viewBox="0 0 700 900" preserveAspectRatio="none" ref={register(`curtain-${side}`) as React.Ref<SVGSVGElement>} aria-hidden="true"><image href={finaleConfig.orangeWashAsset} x={side==="right"?-170:0} width="900" height="900" preserveAspectRatio="xMidYMid slice"/></svg>)}
  <div className="hs-finale__streaks" aria-hidden="true">{streaks.map((y,i)=><svg key={i} className={`hs-finale__streak hs-finale__streak--${i%2?"right":"left"}`} ref={register(`streak-${i}`) as React.Ref<SVGSVGElement>} style={{top:`${y}%`}} viewBox="0 0 500 55" preserveAspectRatio="none"><path d={i%2?"M4 31C82 5 142 24 223 12s161 16 272-5l-16 29c-97 21-187-9-273 8S74 42 4 50Z":"M3 13c93 18 142-9 238 4s153-1 254 14l-22 19c-86-9-161 8-244-4S83 55 3 35Z"}/></svg>)}</div><div className="hs-finale__fragments" aria-hidden="true">{fragments.map(([x,y,s],i)=><span key={i} ref={register(`fragment-${i}`) as React.Ref<HTMLSpanElement>} style={{left:`${x}%`,top:`${y}%`,width:s,height:s*.7,rotate:`${i%2?i*9:-i*7}deg`}}/>)}</div>
 </section>;
}
