export type HSCStory = {
  id: string;
  name: string;
  year: string;
  subject: string;
  quote: string;
  startingPoint?: string;
  whatChanged?: string;
  outcome?: string;
  result?: string;
};

const baseStories: HSCStory[] = [
  { id: 'review-316', name: 'Ruby Nguyen', year: 'Year 12', subject: 'English', quote: 'My English tutor, Ms Lai, has tremendously helped me throughout my whole Year 12. I was able to achieve a mark of 97 for my HSC and got 2nd in the state, boosting my ATAR up to 99.85.', startingPoint: 'Received 16/20 in her first Year 12 English assignment.', whatChanged: 'Small classes, individual help and consistent support from Ms Lai.', outcome: '97 HSC mark, 2nd in the state and a 99.85 ATAR.', result: '99.85 ATAR' },
  { id: 'review-218', name: 'Katherine Ly', year: 'Year 12', subject: 'English, Mathematics, Science', quote: 'From being lost and hating bio in Year 11 to now being a lot more confident in understanding the content as well as applying my knowledge in exams, I can definitely say that my results have improved greatly.' },
  { id: 'review-175', name: 'Jenny Le', year: 'Year 12', subject: 'English, Mathematics, Science', quote: 'Ms Kass has a unique ability to explain complex concepts in a way that is easy to understand, and she always encouraged me to think critically and express myself clearly.' },
  { id: 'review-267', name: 'Michelle Dam', year: 'Year 12', subject: 'English', quote: 'Now, I can definitely write essays with much more confidence in my techniques and structure. Instead, I focus on myself and improve on my mistakes.' },
  { id: 'review-148', name: 'Isabella Huang', year: 'Year 11', subject: 'English, Mathematics, Science', quote: 'It is truly undeniable how much improvement I have made. My confidence in biology skyrocketed as I went into my HSC exams.' },
  { id: 'review-034', name: 'Anna Pham', year: 'Year 12', subject: 'Mathematics', quote: 'My eight year journey at DA transformed me — not only in my studies, but in my attitude and confidence.', outcome: '100% in both 2 Unit and 3 Unit Mathematics and 4th in the state.', result: '4th in NSW' },
  { id: 'review-336', name: 'Selene Dixon', year: 'HSC', subject: 'English, Mathematics, Science', quote: 'Going from a failing grade averaging 40% to securing the top position in the trials with a remarkable 91% is a testament to the support I received.', startingPoint: 'Averaging 40%.', whatChanged: 'Clear explanations, exam preparation and renewed confidence.', outcome: 'Top position in Trials with 91%.', result: '40% → 91%' },
  { id: 'review-039', name: 'Aryan Sharma', year: 'Year 12', subject: 'English, Mathematics, Science', quote: 'Miss explained the easiest and hardest concepts in a matter of moments and my marks went from 5/20 to 18/20. Even in Trials there were massive improvements under time pressure.', result: '5/20 → 18/20' },
  { id: 'review-084', name: 'Cindy Do', year: 'Year 12', subject: 'English, Mathematics, Science', quote: 'My first tutor made English go from unbearable to bearable. Mr King makes maths concepts easier to understand and is really patient when you are unsure of something.' },
  { id: 'review-153', name: 'Jacob Danh', year: 'HSC', subject: 'Business Studies, English, Mathematics', quote: 'DA provides welcoming classrooms with fewer students where teachers constantly provide feedback and accommodate student weaknesses.', outcome: 'Raw 96 in Mathematics 2 Unit.', result: 'Raw 96' },
  { id: 'review-252', name: 'Madison Eung', year: 'Year 11', subject: 'English, Mathematics', quote: 'Her knowledge about how to efficiently complete exams helped me improve my performance and better understand the best way to tackle an English essay and exam paper.' },
  { id: 'review-217', name: 'Katelyn Dinh', year: 'HSC', subject: 'Mathematics', quote: 'He made learning maths really enjoyable. His patience and commitment boosted my confidence and encouraged me to strive for perfection.' },
  { id: 'review-108', name: 'Diana Nguyen', year: 'HSC', subject: 'English, Mathematics', quote: 'DA Tuition provides a fun and friendly environment, as well as encouraging teachers who helped improve my grades from a C to an A.', result: 'C → A' },
  { id: 'review-274', name: 'Mischa Tran', year: 'HSC', subject: 'English, Mathematics, Selective Preparation', quote: 'My improvements in Maths are all thanks to Miss Linda. It is very rewarding to see my improvements in tests and exams and get positive feedback from my parents.' },
  { id: 'review-195', name: 'Joie Lim', year: 'Year 12', subject: 'English, Mathematics', quote: 'Mr Bunsea was my Maths Standard 2 tutor. He is an incredible teacher who is extremely patient and committed to his students’ growth and success.' },
  { id: 'review-149', name: 'Isabella Luong', year: 'Year 11', subject: 'Mathematics', quote: 'Mr Bunsea’s friendliness, sense of humour and ability to break down questions into strategies allowed me to understand and memorise complex questions more easily.' },
  { id: 'review-230', name: 'Khushleen Kaur', year: 'Year 12', subject: 'Mathematics', quote: 'My tutors helped me throughout the years. They were patient and re-explained any concept I was unsure of without hesitation.' },
  { id: 'review-081', name: 'Christine Phung', year: 'HSC', subject: 'Mathematics', quote: 'I had the privilege of learning from exceptional teachers, Mr Bunsea and Miss Anna. I am genuinely grateful for their positive influence on my education.' },
  { id: 'review-122', name: 'Emma Thomas', year: 'Year 12', subject: 'Mathematics', quote: 'Thanks to the support I received at DA, my grades in maths substantially changed. I went from the low 70s to scoring in the 90s and ranked 1st by the end of Year 12.', result: '70s → 90s' },
  { id: 'review-231', name: 'Kim Ma', year: 'HSC', subject: 'English, Mathematics, Science', quote: 'Mr Bunsea broadened my understanding of maths and helped me prepare for the HSC. Mr Danny helped improve my biology marks and understanding of concepts.' },
  { id: 'review-086', name: 'Cindy Nguyen', year: 'HSC', subject: 'Mathematics, Science', quote: 'My tutors are great at explaining complex ideas I struggled to grasp before. Difficult Mathematics Extension 2 concepts and questions became much clearer.' },
  { id: 'review-107', name: 'Diana El Safadi', year: 'Year 11', subject: 'English, Mathematics, Science', quote: 'Mr Danny was my Biology tutor. The way he explains difficult concepts was really well done and his classes were always memorable.' },
  { id: 'review-342', name: 'Sonia Ly', year: 'HSC', subject: 'Business Studies, English, Legal Studies, Mathematics, Science', quote: 'DA has been my home since Year 3. It supports, cares for and educates students not only as teachers but as mentors.' },
  { id: 'review-004', name: 'Adrian Dang', year: 'HSC', subject: 'English, Mathematics', quote: 'For English Advanced, Miss Lai helped me thrive during assignments and exams, boosting my rank by 10 places between semesters and helping me top my class in the Trial exam.', result: '+10 ranks' },
  { id: 'review-312', name: 'Ren Melngu', year: 'HSC', subject: 'English, Mathematics', quote: 'This year in maths my scores have shown constant improvement, with recent exams better than the previous. Finding the fun side of English also helped my marks improve.' },
  { id: 'review-113', name: 'Edison Nguy', year: 'HSC', subject: 'Mathematics', quote: 'When I first enrolled for mathematics I was scared to ask questions, but the caring and supportive atmosphere allowed me to become comfortable and improve.' },
  { id: 'review-142', name: 'Helen Au', year: 'HSC', subject: 'Mathematics', quote: 'When I started with Miss Stephanie, even for a short period, my results significantly improved. She is kind and knows what her students need to improve.' },
  { id: 'review-079', name: 'Christina Lee', year: 'HSC', subject: 'English', quote: 'After studying under Miss Lai for four years she brought out my love for English and inspired me to stay determined and passionate towards my work.' },
  { id: 'review-110', name: 'Dorothy Pham', year: 'HSC', subject: 'Mathematics', quote: 'Before DA I had no confidence in Mathematics or walking into exams. Each lesson opened my eyes and I started enjoying maths.' },
  { id: 'review-368', name: 'Trish Nguyen', year: 'Year 12', subject: 'English, Mathematics', quote: 'My tutors instilled me with so much confidence and knowledge. They somehow turned my hatred for Maths and English into something I love and enjoy.' },
  { id: 'review-333', name: 'Sasha Cio', year: 'Year 12', subject: 'Business Studies, English, Mathematics', quote: 'I received endless support from all my tutors, leading to a dramatic improvement in my overall grades. Their patience and effective teaching helped me score 97% on my latest exam.', result: '97%' },
  { id: 'review-129', name: 'Florence Nguyen', year: 'HSC', subject: 'English, Mathematics', quote: 'DA helped raise my grades tremendously. I recently scored full marks on my English assessment task and am doing well in maths with Miss Anna’s help.', result: 'Full marks' },
];

const verifiedQuotes: Record<string, string> = {
  'review-316': 'My English tutor, Ms Lai, has tremendously helped me throughout my whole year 12. Even more surprisingly, I was able to achieve a mark of 97 for my HSC and got 2nd in the state, boosting my ATAR up to 99.85.',
  'review-218': 'From being lost and hating bio in year 11 to now being a lot more confident in understanding the content as well as applying my knowledge in exams, I can definitely say that my results have improved greatly. With having minor issues such as writing essays and adapting it to exams on the day, Miss Kathleen has taught…',
  'review-175': `Ms Kass has a unique ability to explain complex concepts in a way that's easy to understand, and she always encouraged me to think critically and express myself clearly. I am very greatfull that I got the opportunity to learn from Mr Danny as he is a great tutor I recently started learning with Mr king and I have to…`,
  'review-267': 'Now, I can definitely write essays with much more confidence in my techniques and structure. Instead, I focus on myself and improve on my mistakes.',
  'review-148': 'Although I have only attended this tuition for a year and a half, it is truly undeniable how much improvement I have made over the year after attending DA as I go into my HSC exams! It is all because of Mr Danny that my confidence in biology skyrocketed, as I now go into my HSC exams with a comfortable overall rank of…',
  'review-034': 'My eight year journey at DA transformed me - not only in my studies, but in my attitude and confidence. Her strict high expectations and no-sooking attitude pushed me to perform at 110%, always aiming to get 100% for every exam.',
  'review-336': 'Going from a failing grade (averaging 40%) to securing the top position in the trials with a remarkable 91% is a testament to Mr. Additionally, achieving an assignment mark of 99 and my final ranking 6th out of 100+ students showed that his guidance not only improved my math skills but also rekindled my love for the…',
  'review-039': 'Miss have explained me the easiest and hardest concepts in a matter of moments and my marks west from 5/20 to 18/20. Even in trials there were massive improvements under time pressure as well.',
  'review-084': 'My first ever tutor here was Miss Jenny, she has made English go from unbearable to bearable. Mr King is such a great maths tutor; he really makes concepts easier to understand and is really patient when you are unsure of something.',
  'review-153': 'What makes DA’s teaching style special is being able to provide welcoming classrooms with fewer students where the teachers constantly provide feedback and accommodate to student weaknesses, for example I’ve had many upcoming exams where my teacher Mr King would print out and organise resources made customed to my…',
  'review-252': 'Her knowledge and understanding about how to efficiently complete exams (specifically paper 1),from her past experience helped me improve my performance in exams and helped me better understand the best way to tackle an English essay/ exam paper. Mr King and Ms Amanda were amazing tutors who helped me go from 40% in…',
  'review-217': 'He’s made learning math really enjoyable, with his patience and commitment it had really boosted my confidence in math and has scored me high marks. His confidence in my skills has encouraged me to strive for perfection and to push myself to my limits.',
  'review-108': 'DA Tuition provides a fun, and friendly environment, as well as encouraging teachers that will help you improve your grades from a C to an A. Overall, DA Tuition is an amazing place to improve your grades and understand the subjects better.',
  'review-274': 'My improvements in Maths are all thanks to Miss Linda 😉 it very rewarding to see my improvements in tests and exams, and get positive feedback from my parents. I really hope Miss Linda continues to teach our class, I believe she is the only teacher that fully understand our GAT students’ traits and knows the insides…',
  'review-195': 'Mr Bunsea was my Maths Standard 2 tutor. He is an incredible teacher who is extremely patient and committed to his students growth and success.',
  'review-149': 'I give full credits of my journey in DA to Mr Bunsea as my first tutor and current tutor his friendliness, sense of humour and his ability to break down while also injecting humour into the maths questions in particular strategies to allow me to understand and memorise complex questions in an easier way. As I am going…',
  'review-230': 'Miss Anna, Miss Stephanie, Miss Linda and Mr King are some of the tutors who have helped me throughout the years I have been here. He was very patient with me and re explained any concept I was unsure of without any hesitation.',
  'review-081': 'I had the privilege of learning from exceptional teachers, Mr Bunsea and Miss Anna. I am genuinely grateful for the positive influence Mr Bunsea and Miss Anna had on my education.',
  'review-122': 'This was evident in the he was able to explain concepts that stumped me in a way that was nice and easy to understand. Moreover, towards the end of year 12, I had the privilege of being taught by both Mr Bunsea and Ms Anna who was also a great teacher and was very supportive and great at explaining.',
  'review-231': 'Mr Bunsea has broadened my understanding of maths and helped me prepare for the HSC. Finally, Mr Danny with his extensive knowledge in biology, has helped in improving my marks and my understanding of concepts.',
  'review-086': 'They are also great at explaining complex ideas and concepts which I struggled to grasp before. :) Also, Mr Bunsea, who is my Ext 2 Math teacher, explains difficult math concepts and questions very well.',
  'review-107': 'Mr Danny was my super duper funny biology tutor who had the loudest voice that anyone could hear from a mile away. The way he explains certain concepts was really well done.',
  'review-342': `Da tuition has been my home since year 3 and I'm about to enter HSC, It's the number 1 leading tutor place that supports, cares and educates their students not as teacher but as mentors. Miss Linda (Maths) constantly challenges and motivates me towards an higher mark or rank as she believes and caters my lesson plans…`,
  'review-004': 'I began in private classes in year 3 which helped build the foundation of my learning in the lead up to years 5 and 6, where I had Mr Danny, and without him and his constant support I would not have achieved excellent results in the selective exams. For English advanced I had Miss Lai, and she is the most supportive,…',
  'review-312': 'This year in math my scores have been nothing but constant improvements, recent exams better than the previous. Finding that “fun” side of English would help you to truly enjoy English, thus your marks would positively improve.',
  'review-113': 'As a student here at DA tuition for the past four years, I can’t possibly put into words how much it has helped me improve my grades. When I first enrolled here for mathematics, I was scared to even ask questions to any teachers, but when I was put into Miss Trinh’s class, the caring, supportive atmosphere allowed me…',
  'review-142': 'When I started having Miss Stephanie, even for a short period, my results significantly improve as soon as I joined. Miss Stephanie is very kind, and she knows what her students need to improve.',
  'review-079': 'After studying under Miss Lai for 4 years she has brought out my love for English and has inspired me to stay determined and passionate towards my work. Her charismatic personality in class encourages a fun, bright and collaborative environment and i will forever appreciate her being my teacher and look forward to…',
  'review-110': `Before starting off at DA in year 8, I had no confidence in my Mathematic Class' let alone walking into exams. Other tutoring places did not motivate me and I honestly hated Mathematics for years, but ever since I started off at DA, each lesson would really open up my eyes and I started enjoying Maths.`,
  'review-368': 'As my tutor, he has instilled me with so much confidence and knowledge. These are the tutors that will somehow turn your hatred for Math & English into something you’ll love and enjoy.',
  'review-333': 'I’ve been at DA for 3 years now, and during this time, I’ve received endless support from all my tutors, leading to a dramatic improvement in my overall grades. Thanks to his endless patience and effective teaching methods, I’ve been able to thoroughly understand all my topics and scored 97% on my latest exam.',
  'review-129': 'I’ve been coming to DA for around a year now, and it’s helped raise my grades tremendously !! Recently, I even scored full marks on my English assessment task thanks to Miss Stephanie, and am doing well in maths now with Miss Anna’s help.',
};

export const hscStories = baseStories.map((story) => ({ ...story, quote: verifiedQuotes[story.id] }));
